Repository TeamNewPipe/NewPipeExtractor, pull requests merged in 2023-06, with the labels that each got.

#1072 Fix BandcampRadioStreamExtractorTest.testGetAudioStreams()
  extractor/src/test/java/org/schabi/newpipe/extractor/services/bandcamp/BandcampRadioStreamExtractorTest.java
Labels: bandcamp

#1074 Add more audio media formats and MediaFormat.getAllForMimeType(mimeType)
  extractor/src/main/java/org/schabi/newpipe/extractor/MediaFormat.java
Labels: soundcloud

#1071 Init services at the correct place
  extractor/src/main/java/org/schabi/newpipe/extractor/ServiceList.java
Labels: codequality

#1068 [YouTube] Fix parsing short relative date formats (English only)
  extractor/src/main/java/org/schabi/newpipe/extractor/localization/TimeAgoParser.java
  extractor/src/test/java/org/schabi/newpipe/extractor/utils/TimeagoTest.java
  timeago-parser/raw/unique_patterns.json
  timeago-parser/src/main/java/org/schabi/newpipe/extractor/timeago/patterns/en.java
  timeago-parser/src/main/java/org/schabi/newpipe/extractor/timeago/patterns/en_GB.java
Labels: bug, youtube

#1070 [YouTube] Check whether player responses are valid for all InnerTube clients used
  extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java
Labels: youtube
